### PR TITLE
End game screen

### PR DESCRIPTION
**Pull request by Alianshark**
-change text of GameOver to img
-added reload page button

### CODE REVIEW

**Review by Gehinom — COMMENTED** [review]
Why do you need a div with the id="gameover-button" if it is not used?

**Comment by Alianshark** [comment]
> Why do you need a div with the id="gameover-button" if it is not used?

Just to be, if it needed it is

**Comment by Gehinom** [comment]
> > Why do you need a div with the id="gameover-button" if it is not used?
> 
> Just to be, if it needed it is

If everyone starts adding just in case, it will turn out to be complete bullshit

**Review by Gehinom — CHANGES_REQUESTED** [review]
remove the unused div with id="gameover-button" because it is not used anywhere

**Review by 19thanks96 — APPROVED** [review]

**Review by Gehinom — APPROVED** [review]

**Review by valik-h — APPROVED** [review]

**Pull request merged**
